FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY E-Verland.sln .
COPY Host/*.csproj                    Host/
COPY SharedKernel/*.csproj            SharedKernel/
COPY Tests/*.csproj                   Tests/

RUN dotnet restore

COPY . .
RUN dotnet publish Host/E-Verland.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

USER root
RUN apt-get update && apt-get install -y \
    libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -r appgroup && useradd -r -g appgroup appuser \
    && chown -R appuser:appgroup /app

RUN mkdir -p /app/.aspnet/DataProtection-Keys && \
    chown -R appuser:appgroup /app/.aspnet

USER appuser

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "E-Verland.dll"]