// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Modules.Chat.Infrastructure.Persistence;

#nullable disable

namespace Modules.Chat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Chat.Domain.Conversation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("AdminId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("LastMessageId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("LastMessageAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LastMessagePreview")
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId", "AdminId")
                    .IsUnique()
                    .HasDatabaseName("ix_conversation_userid_adminid");

                b.ToTable("Conversations");
            });

            modelBuilder.Entity("Modules.Chat.Domain.Message", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ConversationId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SenderId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("SentAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ConversationId")
                    .HasDatabaseName("idx_message_conversationid");

                b.HasOne((string)null)
                    .WithMany()
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("Messages");
            });
#pragma warning restore 612, 618
        }
    }
}
